# Generated by Django 5.1.2 on 2024-11-22 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="collaborator_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "collaboration_type",
                    models.CharField(
                        choices=[
                            ("Sponsor", "Sponsor"),
                            ("Partner", "Partner"),
                            ("Volunteer Group", "Volunteer Group"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Impact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("Event", "Event"),
                            ("Achievement", "Achievement"),
                            ("Partnership", "Partnership"),
                            ("Community Outreach", "Community Outreach"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Editor", "Editor"),
                            ("Volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_edit_blogs", models.BooleanField(default=False)),
                ("can_edit_projects", models.BooleanField(default=False)),
                ("can_edit_impacts", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Journal", "Journal"),
                            ("Project", "Project"),
                            ("Impact", "Impact"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="journal_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "related_impacts",
                    models.ManyToManyField(blank=True, to="project.impact"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="impact",
            name="related_blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.journal",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Editor", "Editor"),
                            ("Contributor", "Contributor"),
                            ("Volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("contact_email", models.EmailField(max_length=254)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="journal",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.profile"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Software", "Software"),
                            ("Community Service", "Community Service"),
                            ("Research", "Research"),
                            ("Fundraising", "Fundraising"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("project_link", models.URLField(blank=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_banners/"
                    ),
                ),
                (
                    "funding_status",
                    models.CharField(
                        choices=[
                            ("Funded", "Funded"),
                            ("Seeking Funds", "Seeking Funds"),
                            ("Completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        related_name="projects", to="project.profile"
                    ),
                ),
                (
                    "related_blogs",
                    models.ManyToManyField(blank=True, to="project.journal"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="project.tag")),
            ],
        ),
        migrations.CreateModel(
            name="MediaGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("Image", "Image"),
                            ("Video", "Video"),
                            ("Document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
                ("upload_date", models.DateField(auto_now_add=True)),
                (
                    "related_blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.journal",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="impact",
            name="related_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="tags",
            field=models.ManyToManyField(blank=True, to="project.tag"),
        ),
        migrations.AddField(
            model_name="impact",
            name="tags",
            field=models.ManyToManyField(blank=True, to="project.tag"),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("registration_link", models.URLField(blank=True)),
                (
                    "related_blogs",
                    models.ManyToManyField(blank=True, to="project.journal"),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="project.tag")),
            ],
        ),
    ]
