# Generated by Django 5.1.2 on 2024-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
