# Generated by Django 5.1.2 on 2024-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_collaborator_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="related_impacts",
        ),
        migrations.RemoveField(
            model_name="project",
            name="funding_status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="related_blogs",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="category",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
