# Generated by Django 5.1.2 on 2024-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_journal_related_impacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="related_blogs",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="project.journal"
            ),
        ),
    ]
