# Generated by Django 5.1.2 on 2024-11-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_related_blogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="project/default-profile.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
