# Generated by Django 5.1.2 on 2024-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="can_edit_impacts",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default-profile.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
