# Generated by Django 5.1.2 on 2024-11-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_delete_impact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MediaGallery",
        ),
    ]
