# Generated by Django 5.1.2 on 2024-11-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_delete_mediagallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_links",
            field=models.TextField(blank=True),
        ),
    ]
